### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ronbuchanan** [strongloop/loopback-example-angular-starter#10]
Installed StrongLoop, cloned example...

- npm install
- slc run

Error:

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/Users/ronbuchanan/.nvm/v0.10.28/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-control-channel/node_modules/newline-json/stringifier.js:3:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/ronbuchanan/.nvm/v0.10.28/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-control-channel/node_modules/newline-json/index.js:1:85)
    at Module._compile (module.js:449:26)

**Comment by mrsoto** [comment]
It works for me

**Comment by superkhau** [comment]
See the updated example at https://github.com/strongloop/loopback-example-angular and let me know if you run into any issues there.
